mod decoder;
mod encoder;
use std::{
    fs::File,
    io::{BufWriter, Write},
};

use codegen::Scope;

use crate::UnicodeMapping;
use anyhow::Result;

use self::{
    decoder::{build_complete_decode_table, build_incomplete_decode_table, build_incomplete_lossy_decode_table},
    encoder::build_encoder_internal,
};

pub fn generate_coder(name: &str, definition: UnicodeMapping) -> Result<()> {
    let file_path = format!("../src/code_pages/{}.rs", name.to_lowercase());
    let mut file = BufWriter::new(File::create(file_path)?);
    let code = generate_code(name, definition)?;
    file.write_all(format_code(&code)?.as_bytes())?;
    Ok(())
}

pub fn generate_code(name: &str, definition: UnicodeMapping) -> Result<String> {
    let mut coder = Scope::new();
    coder.push_impl(build_encoder_internal(name, &definition));

    let is_complete = definition.iter().flatten().count() == 256;

    let template = if is_complete {
        include_str!("codegen_helper/templates/complete.rs")
    } else {
        include_str!("codegen_helper/templates/incomplete.rs")
    };

    let is_non_ascii = definition
        .iter()
        .take(128)
        .filter_map(|c| *c)
        .any(|c| !c.is_ascii());

    let decode_helper_name = if is_non_ascii {
        "decode_helper_non_ascii"
    } else {
        "decode_helper"
    };

    let mut replaced_template = template
        .replace("CODERSTRUCT", name)
        .replace("decode_helper", decode_helper_name);

    if is_complete {
        let table = build_complete_decode_table(definition);
        replaced_template = replaced_template.replace("PLACEHOLDER_TABLE", &table);
    } else {
        let table = build_incomplete_decode_table(definition.clone());
        let lossy_table = build_incomplete_lossy_decode_table(definition);
        replaced_template = replaced_template
            .replace("PLACEHOLDER_TABLE", &table)
            .replace("PLACEHOLDER_LOSSY_TABLE", &lossy_table);
    }

    let code = format!(
        "//! Code autogenerated from <https://unicode.org/Public/MAPPINGS/VENDORS/>\n\
         //! See binary codegen crate\n\
         {}\n\
         {}",
        replaced_template,
        coder.to_string(),
    );

    Ok(code)
}

fn format_code(value: &str) -> Result<String> {
    use std::io::Write as _;
    use std::process::{Command, Stdio};

    let mut child = Command::new("rustfmt")
        .args(["--edition", "2021", "--emit", "stdout"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .spawn()?;
    child
        .stdin
        .take()
        .expect("rustfmt stdin")
        .write_all(value.as_bytes())?;
    let output = child.wait_with_output()?;
    if !output.status.success() {
        anyhow::bail!("rustfmt exited with status {}", output.status);
    }
    Ok(String::from_utf8(output.stdout)?)
}
