//! Code autogenerated from <https://unicode.org/Public/MAPPINGS/VENDORS/>
//! See binary codegen crate
#[cfg(feature = "alloc")]
use alloc::borrow::Cow;

use crate::{
    decoder::{self, Entry},
    encoder::Encoder,
    CodePage,
};

#[cfg(feature = "alloc")]
use crate::decoder::complete::decode_helper;

#[cfg(feature = "alloc")]
use crate::{DecodeError, EncodeError};

#[derive(Copy, Clone)]
pub struct CP1254;

impl CP1254 {
    /// Decode CP1254 byte-encoding into UTF-8 string
    ///
    /// # Examples
    ///
    /// ```
    /// use yore::code_pages::CP1254;
    ///
    /// assert_eq!(CP1254.decode(&[116, 101, 120, 116]), "text");
    /// ```
    #[cfg(feature = "alloc")]
    #[inline(always)]
    pub fn decode(self, bytes: &[u8]) -> Cow<'_, str> {
        decode_helper(&DECODE_TABLE, bytes)
    }

    /// Decode a single CP1254 byte into its character.
    ///
    /// Allocation-free, so available without the `alloc` feature. CP1254
    /// is a complete codepage (every byte maps to a character), so this is
    /// infallible and returns `char` directly.
    ///
    /// # Examples
    ///
    /// ```
    /// use yore::code_pages::CP1254;
    ///
    /// assert_eq!(CP1254.decode_byte(b't'), 't');
    /// ```
    #[cfg(feature = "alloc")]
    #[inline(always)]
    pub fn decode_byte(self, b: u8) -> char {
        // The UTF-8 decode table is already in memory for the bulk `decode`
        // path, so decode the entry rather than carrying a second (codepoint)
        // table.
        DECODE_TABLE[b as usize].to_char()
    }

    /// Decode a single CP1254 byte into its character.
    #[cfg(not(feature = "alloc"))]
    #[inline(always)]
    pub fn decode_byte(self, b: u8) -> char {
        // No bulk decoder in this build, so the table stores codepoints
        // directly (same 4 bytes/entry as the UTF-8 table) and this is a load.
        DECODE_TABLE_CHAR[b as usize]
    }

    /// Encode UTF-8 string into CP1254 byte-encoding
    ///
    /// Undefined characters will result in [`EncodeError`]
    ///
    /// # Examples
    ///
    /// ```
    /// use yore::code_pages::CP1254;
    /// use yore::EncodeError;
    ///
    /// assert_eq!(CP1254.encode("text").unwrap(), vec![116, 101, 120, 116]);
    /// assert!(matches!(CP1254.encode("text 🦀"), EncodeError));
    /// ```
    #[cfg(feature = "alloc")]
    #[inline(always)]
    pub fn encode(self, s: &str) -> Result<Cow<'_, [u8]>, EncodeError> {
        self.encode_helper(s, None)
    }

    /// Encode UTF-8 string into CP1254 byte-encoding
    ///
    /// Undefined characters will be replaced with byte `fallback`
    ///
    /// # Examples
    ///
    /// ```
    /// use yore::code_pages::CP1254;
    ///
    /// assert_eq!(CP1254.encode_lossy("text 🦀", 168), vec![116, 101, 120, 116, 32, 168]);
    /// ```
    #[cfg(feature = "alloc")]
    #[inline(always)]
    pub fn encode_lossy(self, s: &str, fallback: u8) -> Cow<'_, [u8]> {
        self.encode_helper(s, Some(fallback)).unwrap()
    }

    /// Encode a single Unicode `char` into its CP1254 byte.
    ///
    /// Returns `None` if the character has no mapping. Allocation-free, so
    /// available without the `alloc` feature; compose with `s.chars()` for
    /// streaming use:
    ///
    /// ```
    /// use yore::code_pages::CP1254;
    ///
    /// let s = "text";
    /// let bytes: Vec<u8> = s.chars().map(|c| CP1254.encode_char(c).unwrap()).collect();
    /// assert_eq!(bytes, vec![116, 101, 120, 116]);
    /// ```
    #[inline]
    pub fn encode_char(self, c: char) -> Option<u8> {
        let mut buf = [0u8; 4];
        let utf8 = c.encode_utf8(&mut buf).as_bytes();
        let mut slice: &[u8] = utf8;
        self.encode_grapheme(&mut slice)
    }
}
impl CodePage for CP1254 {
    #[cfg(feature = "alloc")]
    #[inline(always)]
    fn decode<'a>(&self, bytes: &'a [u8]) -> Result<Cow<'a, str>, DecodeError> {
        Ok((*self).decode(bytes))
    }
}

const DECODE_TABLE: decoder::complete::Table = [
    Entry::new([0x00, 0x00, 0x00], 1),
    Entry::new([0x01, 0x00, 0x00], 1),
    Entry::new([0x02, 0x00, 0x00], 1),
    Entry::new([0x03, 0x00, 0x00], 1),
    Entry::new([0x04, 0x00, 0x00], 1),
    Entry::new([0x05, 0x00, 0x00], 1),
    Entry::new([0x06, 0x00, 0x00], 1),
    Entry::new([0x07, 0x00, 0x00], 1),
    Entry::new([0x08, 0x00, 0x00], 1),
    Entry::new([0x09, 0x00, 0x00], 1),
    Entry::new([0x0A, 0x00, 0x00], 1),
    Entry::new([0x0B, 0x00, 0x00], 1),
    Entry::new([0x0C, 0x00, 0x00], 1),
    Entry::new([0x0D, 0x00, 0x00], 1),
    Entry::new([0x0E, 0x00, 0x00], 1),
    Entry::new([0x0F, 0x00, 0x00], 1),
    Entry::new([0x10, 0x00, 0x00], 1),
    Entry::new([0x11, 0x00, 0x00], 1),
    Entry::new([0x12, 0x00, 0x00], 1),
    Entry::new([0x13, 0x00, 0x00], 1),
    Entry::new([0x14, 0x00, 0x00], 1),
    Entry::new([0x15, 0x00, 0x00], 1),
    Entry::new([0x16, 0x00, 0x00], 1),
    Entry::new([0x17, 0x00, 0x00], 1),
    Entry::new([0x18, 0x00, 0x00], 1),
    Entry::new([0x19, 0x00, 0x00], 1),
    Entry::new([0x1A, 0x00, 0x00], 1),
    Entry::new([0x1B, 0x00, 0x00], 1),
    Entry::new([0x1C, 0x00, 0x00], 1),
    Entry::new([0x1D, 0x00, 0x00], 1),
    Entry::new([0x1E, 0x00, 0x00], 1),
    Entry::new([0x1F, 0x00, 0x00], 1),
    Entry::new([0x20, 0x00, 0x00], 1),
    Entry::new([0x21, 0x00, 0x00], 1),
    Entry::new([0x22, 0x00, 0x00], 1),
    Entry::new([0x23, 0x00, 0x00], 1),
    Entry::new([0x24, 0x00, 0x00], 1),
    Entry::new([0x25, 0x00, 0x00], 1),
    Entry::new([0x26, 0x00, 0x00], 1),
    Entry::new([0x27, 0x00, 0x00], 1),
    Entry::new([0x28, 0x00, 0x00], 1),
    Entry::new([0x29, 0x00, 0x00], 1),
    Entry::new([0x2A, 0x00, 0x00], 1),
    Entry::new([0x2B, 0x00, 0x00], 1),
    Entry::new([0x2C, 0x00, 0x00], 1),
    Entry::new([0x2D, 0x00, 0x00], 1),
    Entry::new([0x2E, 0x00, 0x00], 1),
    Entry::new([0x2F, 0x00, 0x00], 1),
    Entry::new([0x30, 0x00, 0x00], 1),
    Entry::new([0x31, 0x00, 0x00], 1),
    Entry::new([0x32, 0x00, 0x00], 1),
    Entry::new([0x33, 0x00, 0x00], 1),
    Entry::new([0x34, 0x00, 0x00], 1),
    Entry::new([0x35, 0x00, 0x00], 1),
    Entry::new([0x36, 0x00, 0x00], 1),
    Entry::new([0x37, 0x00, 0x00], 1),
    Entry::new([0x38, 0x00, 0x00], 1),
    Entry::new([0x39, 0x00, 0x00], 1),
    Entry::new([0x3A, 0x00, 0x00], 1),
    Entry::new([0x3B, 0x00, 0x00], 1),
    Entry::new([0x3C, 0x00, 0x00], 1),
    Entry::new([0x3D, 0x00, 0x00], 1),
    Entry::new([0x3E, 0x00, 0x00], 1),
    Entry::new([0x3F, 0x00, 0x00], 1),
    Entry::new([0x40, 0x00, 0x00], 1),
    Entry::new([0x41, 0x00, 0x00], 1),
    Entry::new([0x42, 0x00, 0x00], 1),
    Entry::new([0x43, 0x00, 0x00], 1),
    Entry::new([0x44, 0x00, 0x00], 1),
    Entry::new([0x45, 0x00, 0x00], 1),
    Entry::new([0x46, 0x00, 0x00], 1),
    Entry::new([0x47, 0x00, 0x00], 1),
    Entry::new([0x48, 0x00, 0x00], 1),
    Entry::new([0x49, 0x00, 0x00], 1),
    Entry::new([0x4A, 0x00, 0x00], 1),
    Entry::new([0x4B, 0x00, 0x00], 1),
    Entry::new([0x4C, 0x00, 0x00], 1),
    Entry::new([0x4D, 0x00, 0x00], 1),
    Entry::new([0x4E, 0x00, 0x00], 1),
    Entry::new([0x4F, 0x00, 0x00], 1),
    Entry::new([0x50, 0x00, 0x00], 1),
    Entry::new([0x51, 0x00, 0x00], 1),
    Entry::new([0x52, 0x00, 0x00], 1),
    Entry::new([0x53, 0x00, 0x00], 1),
    Entry::new([0x54, 0x00, 0x00], 1),
    Entry::new([0x55, 0x00, 0x00], 1),
    Entry::new([0x56, 0x00, 0x00], 1),
    Entry::new([0x57, 0x00, 0x00], 1),
    Entry::new([0x58, 0x00, 0x00], 1),
    Entry::new([0x59, 0x00, 0x00], 1),
    Entry::new([0x5A, 0x00, 0x00], 1),
    Entry::new([0x5B, 0x00, 0x00], 1),
    Entry::new([0x5C, 0x00, 0x00], 1),
    Entry::new([0x5D, 0x00, 0x00], 1),
    Entry::new([0x5E, 0x00, 0x00], 1),
    Entry::new([0x5F, 0x00, 0x00], 1),
    Entry::new([0x60, 0x00, 0x00], 1),
    Entry::new([0x61, 0x00, 0x00], 1),
    Entry::new([0x62, 0x00, 0x00], 1),
    Entry::new([0x63, 0x00, 0x00], 1),
    Entry::new([0x64, 0x00, 0x00], 1),
    Entry::new([0x65, 0x00, 0x00], 1),
    Entry::new([0x66, 0x00, 0x00], 1),
    Entry::new([0x67, 0x00, 0x00], 1),
    Entry::new([0x68, 0x00, 0x00], 1),
    Entry::new([0x69, 0x00, 0x00], 1),
    Entry::new([0x6A, 0x00, 0x00], 1),
    Entry::new([0x6B, 0x00, 0x00], 1),
    Entry::new([0x6C, 0x00, 0x00], 1),
    Entry::new([0x6D, 0x00, 0x00], 1),
    Entry::new([0x6E, 0x00, 0x00], 1),
    Entry::new([0x6F, 0x00, 0x00], 1),
    Entry::new([0x70, 0x00, 0x00], 1),
    Entry::new([0x71, 0x00, 0x00], 1),
    Entry::new([0x72, 0x00, 0x00], 1),
    Entry::new([0x73, 0x00, 0x00], 1),
    Entry::new([0x74, 0x00, 0x00], 1),
    Entry::new([0x75, 0x00, 0x00], 1),
    Entry::new([0x76, 0x00, 0x00], 1),
    Entry::new([0x77, 0x00, 0x00], 1),
    Entry::new([0x78, 0x00, 0x00], 1),
    Entry::new([0x79, 0x00, 0x00], 1),
    Entry::new([0x7A, 0x00, 0x00], 1),
    Entry::new([0x7B, 0x00, 0x00], 1),
    Entry::new([0x7C, 0x00, 0x00], 1),
    Entry::new([0x7D, 0x00, 0x00], 1),
    Entry::new([0x7E, 0x00, 0x00], 1),
    Entry::new([0x7F, 0x00, 0x00], 1),
    Entry::new([0xE2, 0x82, 0xAC], 3),
    Entry::new([0xC2, 0x81, 0x00], 2),
    Entry::new([0xE2, 0x80, 0x9A], 3),
    Entry::new([0xC6, 0x92, 0x00], 2),
    Entry::new([0xE2, 0x80, 0x9E], 3),
    Entry::new([0xE2, 0x80, 0xA6], 3),
    Entry::new([0xE2, 0x80, 0xA0], 3),
    Entry::new([0xE2, 0x80, 0xA1], 3),
    Entry::new([0xCB, 0x86, 0x00], 2),
    Entry::new([0xE2, 0x80, 0xB0], 3),
    Entry::new([0xC5, 0xA0, 0x00], 2),
    Entry::new([0xE2, 0x80, 0xB9], 3),
    Entry::new([0xC5, 0x92, 0x00], 2),
    Entry::new([0xC2, 0x8D, 0x00], 2),
    Entry::new([0xC2, 0x8E, 0x00], 2),
    Entry::new([0xC2, 0x8F, 0x00], 2),
    Entry::new([0xC2, 0x90, 0x00], 2),
    Entry::new([0xE2, 0x80, 0x98], 3),
    Entry::new([0xE2, 0x80, 0x99], 3),
    Entry::new([0xE2, 0x80, 0x9C], 3),
    Entry::new([0xE2, 0x80, 0x9D], 3),
    Entry::new([0xE2, 0x80, 0xA2], 3),
    Entry::new([0xE2, 0x80, 0x93], 3),
    Entry::new([0xE2, 0x80, 0x94], 3),
    Entry::new([0xCB, 0x9C, 0x00], 2),
    Entry::new([0xE2, 0x84, 0xA2], 3),
    Entry::new([0xC5, 0xA1, 0x00], 2),
    Entry::new([0xE2, 0x80, 0xBA], 3),
    Entry::new([0xC5, 0x93, 0x00], 2),
    Entry::new([0xC2, 0x9D, 0x00], 2),
    Entry::new([0xC2, 0x9E, 0x00], 2),
    Entry::new([0xC5, 0xB8, 0x00], 2),
    Entry::new([0xC2, 0xA0, 0x00], 2),
    Entry::new([0xC2, 0xA1, 0x00], 2),
    Entry::new([0xC2, 0xA2, 0x00], 2),
    Entry::new([0xC2, 0xA3, 0x00], 2),
    Entry::new([0xC2, 0xA4, 0x00], 2),
    Entry::new([0xC2, 0xA5, 0x00], 2),
    Entry::new([0xC2, 0xA6, 0x00], 2),
    Entry::new([0xC2, 0xA7, 0x00], 2),
    Entry::new([0xC2, 0xA8, 0x00], 2),
    Entry::new([0xC2, 0xA9, 0x00], 2),
    Entry::new([0xC2, 0xAA, 0x00], 2),
    Entry::new([0xC2, 0xAB, 0x00], 2),
    Entry::new([0xC2, 0xAC, 0x00], 2),
    Entry::new([0xC2, 0xAD, 0x00], 2),
    Entry::new([0xC2, 0xAE, 0x00], 2),
    Entry::new([0xC2, 0xAF, 0x00], 2),
    Entry::new([0xC2, 0xB0, 0x00], 2),
    Entry::new([0xC2, 0xB1, 0x00], 2),
    Entry::new([0xC2, 0xB2, 0x00], 2),
    Entry::new([0xC2, 0xB3, 0x00], 2),
    Entry::new([0xC2, 0xB4, 0x00], 2),
    Entry::new([0xC2, 0xB5, 0x00], 2),
    Entry::new([0xC2, 0xB6, 0x00], 2),
    Entry::new([0xC2, 0xB7, 0x00], 2),
    Entry::new([0xC2, 0xB8, 0x00], 2),
    Entry::new([0xC2, 0xB9, 0x00], 2),
    Entry::new([0xC2, 0xBA, 0x00], 2),
    Entry::new([0xC2, 0xBB, 0x00], 2),
    Entry::new([0xC2, 0xBC, 0x00], 2),
    Entry::new([0xC2, 0xBD, 0x00], 2),
    Entry::new([0xC2, 0xBE, 0x00], 2),
    Entry::new([0xC2, 0xBF, 0x00], 2),
    Entry::new([0xC3, 0x80, 0x00], 2),
    Entry::new([0xC3, 0x81, 0x00], 2),
    Entry::new([0xC3, 0x82, 0x00], 2),
    Entry::new([0xC3, 0x83, 0x00], 2),
    Entry::new([0xC3, 0x84, 0x00], 2),
    Entry::new([0xC3, 0x85, 0x00], 2),
    Entry::new([0xC3, 0x86, 0x00], 2),
    Entry::new([0xC3, 0x87, 0x00], 2),
    Entry::new([0xC3, 0x88, 0x00], 2),
    Entry::new([0xC3, 0x89, 0x00], 2),
    Entry::new([0xC3, 0x8A, 0x00], 2),
    Entry::new([0xC3, 0x8B, 0x00], 2),
    Entry::new([0xC3, 0x8C, 0x00], 2),
    Entry::new([0xC3, 0x8D, 0x00], 2),
    Entry::new([0xC3, 0x8E, 0x00], 2),
    Entry::new([0xC3, 0x8F, 0x00], 2),
    Entry::new([0xC4, 0x9E, 0x00], 2),
    Entry::new([0xC3, 0x91, 0x00], 2),
    Entry::new([0xC3, 0x92, 0x00], 2),
    Entry::new([0xC3, 0x93, 0x00], 2),
    Entry::new([0xC3, 0x94, 0x00], 2),
    Entry::new([0xC3, 0x95, 0x00], 2),
    Entry::new([0xC3, 0x96, 0x00], 2),
    Entry::new([0xC3, 0x97, 0x00], 2),
    Entry::new([0xC3, 0x98, 0x00], 2),
    Entry::new([0xC3, 0x99, 0x00], 2),
    Entry::new([0xC3, 0x9A, 0x00], 2),
    Entry::new([0xC3, 0x9B, 0x00], 2),
    Entry::new([0xC3, 0x9C, 0x00], 2),
    Entry::new([0xC4, 0xB0, 0x00], 2),
    Entry::new([0xC5, 0x9E, 0x00], 2),
    Entry::new([0xC3, 0x9F, 0x00], 2),
    Entry::new([0xC3, 0xA0, 0x00], 2),
    Entry::new([0xC3, 0xA1, 0x00], 2),
    Entry::new([0xC3, 0xA2, 0x00], 2),
    Entry::new([0xC3, 0xA3, 0x00], 2),
    Entry::new([0xC3, 0xA4, 0x00], 2),
    Entry::new([0xC3, 0xA5, 0x00], 2),
    Entry::new([0xC3, 0xA6, 0x00], 2),
    Entry::new([0xC3, 0xA7, 0x00], 2),
    Entry::new([0xC3, 0xA8, 0x00], 2),
    Entry::new([0xC3, 0xA9, 0x00], 2),
    Entry::new([0xC3, 0xAA, 0x00], 2),
    Entry::new([0xC3, 0xAB, 0x00], 2),
    Entry::new([0xC3, 0xAC, 0x00], 2),
    Entry::new([0xC3, 0xAD, 0x00], 2),
    Entry::new([0xC3, 0xAE, 0x00], 2),
    Entry::new([0xC3, 0xAF, 0x00], 2),
    Entry::new([0xC4, 0x9F, 0x00], 2),
    Entry::new([0xC3, 0xB1, 0x00], 2),
    Entry::new([0xC3, 0xB2, 0x00], 2),
    Entry::new([0xC3, 0xB3, 0x00], 2),
    Entry::new([0xC3, 0xB4, 0x00], 2),
    Entry::new([0xC3, 0xB5, 0x00], 2),
    Entry::new([0xC3, 0xB6, 0x00], 2),
    Entry::new([0xC3, 0xB7, 0x00], 2),
    Entry::new([0xC3, 0xB8, 0x00], 2),
    Entry::new([0xC3, 0xB9, 0x00], 2),
    Entry::new([0xC3, 0xBA, 0x00], 2),
    Entry::new([0xC3, 0xBB, 0x00], 2),
    Entry::new([0xC3, 0xBC, 0x00], 2),
    Entry::new([0xC4, 0xB1, 0x00], 2),
    Entry::new([0xC5, 0x9F, 0x00], 2),
    Entry::new([0xC3, 0xBF, 0x00], 2),
];

// In the no-alloc build there is no bulk decoder, so `DECODE_TABLE` is consumed
// only by this const-eval and is never emitted; `DECODE_TABLE_CHAR` (same size)
// takes its place in rodata and makes `decode_byte` a single load.
#[cfg(not(feature = "alloc"))]
const DECODE_TABLE_CHAR: [char; 256] = {
    let mut t = ['\0'; 256];
    let mut i = 0;
    while i < 256 {
        t[i] = DECODE_TABLE[i].to_char();
        i += 1;
    }
    t
};

impl Encoder for CP1254 {
    #[doc(hidden)]
    #[inline]
    fn encode_grapheme(&self, bytes: &mut &[u8]) -> Option<u8> {
        let (&a, rest) = bytes.split_first().unwrap();
        Some(match (a, &bytes) {
            (0x00..=0x7F, _) => {
                *bytes = rest;
                a
            }
            (0xC2, [_, b, ..]) => {
                *bytes = &bytes[2..];
                match b {
                    0x81 => 0x81,
                    0x8D => 0x8D,
                    0x8E => 0x8E,
                    0x8F => 0x8F,
                    0x90 => 0x90,
                    0x9D => 0x9D,
                    0x9E => 0x9E,
                    0xA0 => 0xA0,
                    0xA1 => 0xA1,
                    0xA2 => 0xA2,
                    0xA3 => 0xA3,
                    0xA4 => 0xA4,
                    0xA5 => 0xA5,
                    0xA6 => 0xA6,
                    0xA7 => 0xA7,
                    0xA8 => 0xA8,
                    0xA9 => 0xA9,
                    0xAA => 0xAA,
                    0xAB => 0xAB,
                    0xAC => 0xAC,
                    0xAD => 0xAD,
                    0xAE => 0xAE,
                    0xAF => 0xAF,
                    0xB0 => 0xB0,
                    0xB1 => 0xB1,
                    0xB2 => 0xB2,
                    0xB3 => 0xB3,
                    0xB4 => 0xB4,
                    0xB5 => 0xB5,
                    0xB6 => 0xB6,
                    0xB7 => 0xB7,
                    0xB8 => 0xB8,
                    0xB9 => 0xB9,
                    0xBA => 0xBA,
                    0xBB => 0xBB,
                    0xBC => 0xBC,
                    0xBD => 0xBD,
                    0xBE => 0xBE,
                    0xBF => 0xBF,
                    _ => return None,
                }
            }
            (0xC3, [_, b, ..]) => {
                *bytes = &bytes[2..];
                match b {
                    0x80 => 0xC0,
                    0x81 => 0xC1,
                    0x82 => 0xC2,
                    0x83 => 0xC3,
                    0x84 => 0xC4,
                    0x85 => 0xC5,
                    0x86 => 0xC6,
                    0x87 => 0xC7,
                    0x88 => 0xC8,
                    0x89 => 0xC9,
                    0x8A => 0xCA,
                    0x8B => 0xCB,
                    0x8C => 0xCC,
                    0x8D => 0xCD,
                    0x8E => 0xCE,
                    0x8F => 0xCF,
                    0x91 => 0xD1,
                    0x92 => 0xD2,
                    0x93 => 0xD3,
                    0x94 => 0xD4,
                    0x95 => 0xD5,
                    0x96 => 0xD6,
                    0x97 => 0xD7,
                    0x98 => 0xD8,
                    0x99 => 0xD9,
                    0x9A => 0xDA,
                    0x9B => 0xDB,
                    0x9C => 0xDC,
                    0x9F => 0xDF,
                    0xA0 => 0xE0,
                    0xA1 => 0xE1,
                    0xA2 => 0xE2,
                    0xA3 => 0xE3,
                    0xA4 => 0xE4,
                    0xA5 => 0xE5,
                    0xA6 => 0xE6,
                    0xA7 => 0xE7,
                    0xA8 => 0xE8,
                    0xA9 => 0xE9,
                    0xAA => 0xEA,
                    0xAB => 0xEB,
                    0xAC => 0xEC,
                    0xAD => 0xED,
                    0xAE => 0xEE,
                    0xAF => 0xEF,
                    0xB1 => 0xF1,
                    0xB2 => 0xF2,
                    0xB3 => 0xF3,
                    0xB4 => 0xF4,
                    0xB5 => 0xF5,
                    0xB6 => 0xF6,
                    0xB7 => 0xF7,
                    0xB8 => 0xF8,
                    0xB9 => 0xF9,
                    0xBA => 0xFA,
                    0xBB => 0xFB,
                    0xBC => 0xFC,
                    0xBF => 0xFF,
                    _ => return None,
                }
            }
            (0xC4, [_, b, ..]) => {
                *bytes = &bytes[2..];
                match b {
                    0x9E => 0xD0,
                    0xB0 => 0xDD,
                    0x9F => 0xF0,
                    0xB1 => 0xFD,
                    _ => return None,
                }
            }
            (0xC5, [_, b, ..]) => {
                *bytes = &bytes[2..];
                match b {
                    0xA0 => 0x8A,
                    0x92 => 0x8C,
                    0xA1 => 0x9A,
                    0x93 => 0x9C,
                    0xB8 => 0x9F,
                    0x9E => 0xDE,
                    0x9F => 0xFE,
                    _ => return None,
                }
            }
            (0xC6, [_, b, ..]) => {
                *bytes = &bytes[2..];
                match b {
                    0x92 => 0x83,
                    _ => return None,
                }
            }
            (0xCB, [_, b, ..]) => {
                *bytes = &bytes[2..];
                match b {
                    0x86 => 0x88,
                    0x9C => 0x98,
                    _ => return None,
                }
            }
            (0xE2, [_, b, c, ..]) => {
                *bytes = &bytes[3..];
                match b {
                    0x80 => match c {
                        0x9A => 0x82,
                        0x9E => 0x84,
                        0xA6 => 0x85,
                        0xA0 => 0x86,
                        0xA1 => 0x87,
                        0xB0 => 0x89,
                        0xB9 => 0x8B,
                        0x98 => 0x91,
                        0x99 => 0x92,
                        0x9C => 0x93,
                        0x9D => 0x94,
                        0xA2 => 0x95,
                        0x93 => 0x96,
                        0x94 => 0x97,
                        0xBA => 0x9B,
                        _ => return None,
                    },
                    0x82 => match c {
                        0xAC => 0x80,
                        _ => return None,
                    },
                    0x84 => match c {
                        0xA2 => 0x99,
                        _ => return None,
                    },
                    _ => return None,
                }
            }
            (0xC2..=0xDF, _) => {
                *bytes = &bytes[2..];
                return None;
            }
            (0xE0..=0xEF, _) => {
                *bytes = &bytes[3..];
                return None;
            }
            (0xF0..=0xF4, _) => {
                *bytes = &bytes[4..];
                return None;
            }
            _ => panic!(),
        })
    }
}
