//! Code autogenerated from <https://unicode.org/Public/MAPPINGS/VENDORS/>
//! See binary codegen crate
#[cfg(feature = "alloc")]
use alloc::borrow::Cow;

use crate::{
    decoder::{self, CompleteEntry},
    encoder::Encoder,
    CodePage,
};

#[cfg(feature = "alloc")]
use crate::decoder::complete::decode_helper;

#[cfg(feature = "alloc")]
use crate::{DecodeError, EncodeError};

#[derive(Copy, Clone)]
pub struct CP866;

impl CP866 {
    /// Decode CP866 byte-encoding into UTF-8 string
    ///
    /// # Examples
    ///
    /// ```
    /// use yore::code_pages::CP866;
    ///
    /// assert_eq!(CP866.decode(&[116, 101, 120, 116]), "text");
    /// ```
    #[cfg(feature = "alloc")]
    #[inline(always)]
    pub fn decode(self, bytes: &[u8]) -> Cow<'_, str> {
        decode_helper(&DECODE_TABLE, bytes)
    }

    /// Decode a single CP866 byte into its character.
    ///
    /// Allocation-free, so available without the `alloc` feature. CP866
    /// is a complete codepage (every byte maps to a character), so this is
    /// infallible and returns `char` directly.
    ///
    /// # Examples
    ///
    /// ```
    /// use yore::code_pages::CP866;
    ///
    /// assert_eq!(CP866.decode_byte(b't'), 't');
    /// ```
    #[cfg(feature = "alloc")]
    #[inline(always)]
    pub fn decode_byte(self, b: u8) -> char {
        // The UTF-8 decode table is already in memory for the bulk `decode`
        // path, so decode the entry's stored bytes from the length we have
        // rather than carrying a second (codepoint) table.
        let e = DECODE_TABLE[b as usize];
        let cp = match e.len {
            1 => e.buf[0] as u32,
            2 => ((e.buf[0] as u32 & 0x1F) << 6) | (e.buf[1] as u32 & 0x3F),
            _ => {
                ((e.buf[0] as u32 & 0x0F) << 12)
                    | ((e.buf[1] as u32 & 0x3F) << 6)
                    | (e.buf[2] as u32 & 0x3F)
            }
        };
        // SAFETY: table contents are valid UTF-8 for exactly one scalar value.
        unsafe { char::from_u32_unchecked(cp) }
    }

    /// Decode a single CP866 byte into its character.
    #[cfg(not(feature = "alloc"))]
    #[inline(always)]
    pub fn decode_byte(self, b: u8) -> char {
        // No bulk decoder in this build, so the table stores codepoints
        // directly (same 4 bytes/entry as the UTF-8 table) and this is a load.
        DECODE_TABLE_CHAR[b as usize]
    }

    /// Encode UTF-8 string into CP866 byte-encoding
    ///
    /// Undefined characters will result in [`EncodeError`]
    ///
    /// # Examples
    ///
    /// ```
    /// use yore::code_pages::CP866;
    /// use yore::EncodeError;
    ///
    /// assert_eq!(CP866.encode("text").unwrap(), vec![116, 101, 120, 116]);
    /// assert!(matches!(CP866.encode("text 🦀"), EncodeError));
    /// ```
    #[cfg(feature = "alloc")]
    #[inline(always)]
    pub fn encode(self, s: &str) -> Result<Cow<'_, [u8]>, EncodeError> {
        self.encode_helper(s, None)
    }

    /// Encode UTF-8 string into CP866 byte-encoding
    ///
    /// Undefined characters will be replaced with byte `fallback`
    ///
    /// # Examples
    ///
    /// ```
    /// use yore::code_pages::CP866;
    ///
    /// assert_eq!(CP866.encode_lossy("text 🦀", 168), vec![116, 101, 120, 116, 32, 168]);
    /// ```
    #[cfg(feature = "alloc")]
    #[inline(always)]
    pub fn encode_lossy(self, s: &str, fallback: u8) -> Cow<'_, [u8]> {
        self.encode_helper(s, Some(fallback)).unwrap()
    }

    /// Encode a single Unicode `char` into its CP866 byte.
    ///
    /// Returns `None` if the character has no mapping. Allocation-free, so
    /// available without the `alloc` feature; compose with `s.chars()` for
    /// streaming use:
    ///
    /// ```
    /// use yore::code_pages::CP866;
    ///
    /// let s = "text";
    /// let bytes: Vec<u8> = s.chars().map(|c| CP866.encode_char(c).unwrap()).collect();
    /// assert_eq!(bytes, vec![116, 101, 120, 116]);
    /// ```
    #[inline]
    pub fn encode_char(self, c: char) -> Option<u8> {
        let mut buf = [0u8; 4];
        let utf8 = c.encode_utf8(&mut buf).as_bytes();
        let mut slice: &[u8] = utf8;
        self.encode_grapheme(&mut slice)
    }
}
impl CodePage for CP866 {
    #[cfg(feature = "alloc")]
    #[inline(always)]
    fn decode<'a>(&self, bytes: &'a [u8]) -> Result<Cow<'a, str>, DecodeError> {
        Ok((*self).decode(bytes))
    }
}

const DECODE_TABLE: decoder::complete::Table = [
    CompleteEntry {
        buf: [0x00, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x01, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x02, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x03, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x04, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x05, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x06, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x07, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x08, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x09, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x0A, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x0B, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x0C, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x0D, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x0E, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x0F, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x10, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x11, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x12, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x13, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x14, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x15, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x16, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x17, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x18, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x19, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x1A, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x1B, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x1C, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x1D, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x1E, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x1F, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x20, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x21, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x22, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x23, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x24, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x25, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x26, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x27, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x28, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x29, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x2A, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x2B, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x2C, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x2D, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x2E, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x2F, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x30, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x31, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x32, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x33, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x34, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x35, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x36, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x37, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x38, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x39, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x3A, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x3B, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x3C, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x3D, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x3E, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x3F, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x40, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x41, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x42, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x43, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x44, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x45, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x46, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x47, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x48, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x49, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x4A, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x4B, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x4C, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x4D, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x4E, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x4F, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x50, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x51, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x52, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x53, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x54, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x55, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x56, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x57, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x58, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x59, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x5A, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x5B, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x5C, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x5D, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x5E, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x5F, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x60, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x61, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x62, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x63, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x64, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x65, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x66, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x67, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x68, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x69, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x6A, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x6B, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x6C, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x6D, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x6E, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x6F, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x70, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x71, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x72, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x73, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x74, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x75, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x76, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x77, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x78, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x79, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x7A, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x7B, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x7C, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x7D, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x7E, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0x7F, 0x00, 0x00],
        len: 1,
    },
    CompleteEntry {
        buf: [0xD0, 0x90, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x91, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x92, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x93, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x94, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x95, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x96, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x97, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x98, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x99, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x9A, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x9B, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x9C, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x9D, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x9E, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x9F, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA0, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA1, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA2, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA3, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA4, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA5, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA6, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA7, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA8, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xA9, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xAA, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xAB, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xAC, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xAD, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xAE, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xAF, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB0, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB1, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB2, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB3, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB4, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB5, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB6, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB7, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB8, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xB9, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xBA, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xBB, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xBC, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xBD, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xBE, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0xBF, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xE2, 0x96, 0x91],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x96, 0x92],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x96, 0x93],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0x82],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0xA4],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA1],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA2],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x96],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x95],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA3],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x91],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x97],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x9D],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x9C],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x9B],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0x90],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0x94],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0xB4],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0xAC],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0x9C],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0x80],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0xBC],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x9E],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x9F],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x9A],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x94],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA9],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA6],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA0],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x90],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xAC],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA7],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA8],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA4],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xA5],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x99],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x98],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x92],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0x93],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xAB],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x95, 0xAA],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0x98],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x94, 0x8C],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x96, 0x88],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x96, 0x84],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x96, 0x8C],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x96, 0x90],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x96, 0x80],
        len: 3,
    },
    CompleteEntry {
        buf: [0xD1, 0x80, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x81, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x82, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x83, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x84, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x85, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x86, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x87, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x88, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x89, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x8A, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x8B, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x8C, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x8D, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x8E, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x8F, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x81, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x91, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x84, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x94, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x87, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x97, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD0, 0x8E, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xD1, 0x9E, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xC2, 0xB0, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xE2, 0x88, 0x99],
        len: 3,
    },
    CompleteEntry {
        buf: [0xC2, 0xB7, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xE2, 0x88, 0x9A],
        len: 3,
    },
    CompleteEntry {
        buf: [0xE2, 0x84, 0x96],
        len: 3,
    },
    CompleteEntry {
        buf: [0xC2, 0xA4, 0x00],
        len: 2,
    },
    CompleteEntry {
        buf: [0xE2, 0x96, 0xA0],
        len: 3,
    },
    CompleteEntry {
        buf: [0xC2, 0xA0, 0x00],
        len: 2,
    },
];

// In the no-alloc build there is no bulk decoder, so `DECODE_TABLE` is consumed
// only by this const-eval and is never emitted; `DECODE_TABLE_CHAR` (same size)
// takes its place in rodata and makes `decode_byte` a single load.
#[cfg(not(feature = "alloc"))]
const DECODE_TABLE_CHAR: [char; 256] = {
    let mut t = ['\0'; 256];
    let mut i = 0;
    while i < 256 {
        let e = DECODE_TABLE[i];
        t[i] = decoder::entry_to_char(e.buf, e.len as u32);
        i += 1;
    }
    t
};

impl Encoder for CP866 {
    #[doc(hidden)]
    #[inline]
    fn encode_grapheme(&self, bytes: &mut &[u8]) -> Option<u8> {
        let (&a, rest) = bytes.split_first().unwrap();
        Some(match (a, &bytes) {
            (0x00..=0x7F, _) => {
                *bytes = rest;
                a
            }
            (0xC2, [_, b, ..]) => {
                *bytes = &bytes[2..];
                match b {
                    0xB0 => 0xF8,
                    0xB7 => 0xFA,
                    0xA4 => 0xFD,
                    0xA0 => 0xFF,
                    _ => return None,
                }
            }
            (0xD0, [_, b, ..]) => {
                *bytes = &bytes[2..];
                match b {
                    0x90 => 0x80,
                    0x91 => 0x81,
                    0x92 => 0x82,
                    0x93 => 0x83,
                    0x94 => 0x84,
                    0x95 => 0x85,
                    0x96 => 0x86,
                    0x97 => 0x87,
                    0x98 => 0x88,
                    0x99 => 0x89,
                    0x9A => 0x8A,
                    0x9B => 0x8B,
                    0x9C => 0x8C,
                    0x9D => 0x8D,
                    0x9E => 0x8E,
                    0x9F => 0x8F,
                    0xA0 => 0x90,
                    0xA1 => 0x91,
                    0xA2 => 0x92,
                    0xA3 => 0x93,
                    0xA4 => 0x94,
                    0xA5 => 0x95,
                    0xA6 => 0x96,
                    0xA7 => 0x97,
                    0xA8 => 0x98,
                    0xA9 => 0x99,
                    0xAA => 0x9A,
                    0xAB => 0x9B,
                    0xAC => 0x9C,
                    0xAD => 0x9D,
                    0xAE => 0x9E,
                    0xAF => 0x9F,
                    0xB0 => 0xA0,
                    0xB1 => 0xA1,
                    0xB2 => 0xA2,
                    0xB3 => 0xA3,
                    0xB4 => 0xA4,
                    0xB5 => 0xA5,
                    0xB6 => 0xA6,
                    0xB7 => 0xA7,
                    0xB8 => 0xA8,
                    0xB9 => 0xA9,
                    0xBA => 0xAA,
                    0xBB => 0xAB,
                    0xBC => 0xAC,
                    0xBD => 0xAD,
                    0xBE => 0xAE,
                    0xBF => 0xAF,
                    0x81 => 0xF0,
                    0x84 => 0xF2,
                    0x87 => 0xF4,
                    0x8E => 0xF6,
                    _ => return None,
                }
            }
            (0xD1, [_, b, ..]) => {
                *bytes = &bytes[2..];
                match b {
                    0x80 => 0xE0,
                    0x81 => 0xE1,
                    0x82 => 0xE2,
                    0x83 => 0xE3,
                    0x84 => 0xE4,
                    0x85 => 0xE5,
                    0x86 => 0xE6,
                    0x87 => 0xE7,
                    0x88 => 0xE8,
                    0x89 => 0xE9,
                    0x8A => 0xEA,
                    0x8B => 0xEB,
                    0x8C => 0xEC,
                    0x8D => 0xED,
                    0x8E => 0xEE,
                    0x8F => 0xEF,
                    0x91 => 0xF1,
                    0x94 => 0xF3,
                    0x97 => 0xF5,
                    0x9E => 0xF7,
                    _ => return None,
                }
            }
            (0xE2, [_, b, c, ..]) => {
                *bytes = &bytes[3..];
                match b {
                    0x84 => match c {
                        0x96 => 0xFC,
                        _ => return None,
                    },
                    0x88 => match c {
                        0x99 => 0xF9,
                        0x9A => 0xFB,
                        _ => return None,
                    },
                    0x94 => match c {
                        0x82 => 0xB3,
                        0xA4 => 0xB4,
                        0x90 => 0xBF,
                        0x94 => 0xC0,
                        0xB4 => 0xC1,
                        0xAC => 0xC2,
                        0x9C => 0xC3,
                        0x80 => 0xC4,
                        0xBC => 0xC5,
                        0x98 => 0xD9,
                        0x8C => 0xDA,
                        _ => return None,
                    },
                    0x95 => match c {
                        0xA1 => 0xB5,
                        0xA2 => 0xB6,
                        0x96 => 0xB7,
                        0x95 => 0xB8,
                        0xA3 => 0xB9,
                        0x91 => 0xBA,
                        0x97 => 0xBB,
                        0x9D => 0xBC,
                        0x9C => 0xBD,
                        0x9B => 0xBE,
                        0x9E => 0xC6,
                        0x9F => 0xC7,
                        0x9A => 0xC8,
                        0x94 => 0xC9,
                        0xA9 => 0xCA,
                        0xA6 => 0xCB,
                        0xA0 => 0xCC,
                        0x90 => 0xCD,
                        0xAC => 0xCE,
                        0xA7 => 0xCF,
                        0xA8 => 0xD0,
                        0xA4 => 0xD1,
                        0xA5 => 0xD2,
                        0x99 => 0xD3,
                        0x98 => 0xD4,
                        0x92 => 0xD5,
                        0x93 => 0xD6,
                        0xAB => 0xD7,
                        0xAA => 0xD8,
                        _ => return None,
                    },
                    0x96 => match c {
                        0x91 => 0xB0,
                        0x92 => 0xB1,
                        0x93 => 0xB2,
                        0x88 => 0xDB,
                        0x84 => 0xDC,
                        0x8C => 0xDD,
                        0x90 => 0xDE,
                        0x80 => 0xDF,
                        0xA0 => 0xFE,
                        _ => return None,
                    },
                    _ => return None,
                }
            }
            (0xC2..=0xDF, _) => {
                *bytes = &bytes[2..];
                return None;
            }
            (0xE0..=0xEF, _) => {
                *bytes = &bytes[3..];
                return None;
            }
            (0xF0..=0xF4, _) => {
                *bytes = &bytes[4..];
                return None;
            }
            _ => panic!(),
        })
    }
}
